### ISSUE TITLE
Device status disconnected

### ISSUE THREAD

**Issue by NiranjanRavi1993** [ibm-watson-iot/a71ch-doorLock#1]
Hi,
  I updated my project files and I transmitting the data in cPayload.  In my Watson platform, I could see the **logs that token authentication successful whenever I make the transaction** but my device status is showing as disconnected and in **recent events tab** I cannot see any data!

**Comment by rdasgupt** [comment]
Are you working with FRDM board or MCIMC6UL?
If device status in platform is disconnected, then you need to check log messages on client code. Check for errors returned by publish API.

**Comment by NiranjanRavi1993** [comment]
I am working with FRDM K64F board. There is no error being returned by publish API.  When I restart the device, only logs are being generated and no errors[Both from MCU Xpresso and in the cloud]. This is the demo application which I tried. Surprisingly, this demo was working fine two months back when I tried! Now it is not working.!

**Comment by NiranjanRavi1993** [comment]
hi, now I am able to see the data under tab state. It is not showing under recent events and still, the device status is disconnected. 
Also, the QoS values are working at random times. Sometimes, the data in QoS1 is showing in the cloud and sometimes QoS0.  No pattern! I am not able to understand what is causing this issue!

**Comment by rdasgupt** [comment]
Are you using this sample APP without any modification (Node-red and device code that runs on FRDM board)? 

QoS0 service is not guaranteed to be delivered. Message may be dropped due to many reasons including networking issues. Refer to the following link for QoS definition:
https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/qos.html

The fact that the client connection state on platform is disconnected, I suspect there is some network connectivity issue between your device and WIoT platform.  

This sample APP for FRDM board uses MQTT client code bundled with NXP SDK. You may like to check NXP site for details on the client code.

**Comment by NiranjanRavi1993** [comment]
Hi,
    Sorry for the delayed reply. Yes, I am using the same demo application. 
1. When I ran the python publish script, I am able to see all the data which I send under tab "Events".
2. But when I use QoS methods (1 and 2), a data is being sent to the cloud and I can see it in the tab "State". But when the next data is being sent, it replaces the initial data. 
When I used the python script(point 1), I can witness all the data but why does not it happen when I use mqtt and QoS method? please let me know if my understanding is correct. 
Thank you

**Comment by NiranjanRavi1993** [comment]
Everything is working fine now! Thank you
